### ISSUE TITLE
抖音报错

### ISSUE THREAD

**Issue by Coaixy** [XiaoXinYo/Tiktok_Barrage#7]
@XiaoXinYo 
报错信息：
Traceback (most recent call last):
  File "C:\Users\Coaixy\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\server.py", line 232, in handler
    await self.ws_handler(self)
  File "C:\Users\Coaixy\Desktop\Live_Barrage\TikTok\example\barrage.py", line 19, in run
    await handle(websocket)
  File "C:\Users\Coaixy\Desktop\Live_Barrage\TikTok\example\barrage.py", line 14, in handle
    print('{:10s} | {:10s} | {:10s}'.format(data_count.get('type'), data_count.get('username'), data_count.get('content')))
TypeError: unsupported format string passed to NoneType.__format__

**Comment by ykaiqx** [comment]
已修复
